// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTm-6a4HxUveqechjuTADxTVYjqTQZtyU',
    appId: '1:54532140724:web:9ef05c361b7e672a8071e1',
    messagingSenderId: '54532140724',
    projectId: 'expensexpert-b34c3',
    authDomain: 'expensexpert-b34c3.firebaseapp.com',
    storageBucket: 'expensexpert-b34c3.appspot.com',
    measurementId: 'G-GERPTVZCDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxbB9wGIPj3gvDXsrd0L5gpQr5iccXbWc',
    appId: '1:54532140724:android:949a2933f801cde48071e1',
    messagingSenderId: '54532140724',
    projectId: 'expensexpert-b34c3',
    storageBucket: 'expensexpert-b34c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq9rRgALAyFxJk7YbpZ8Efvp7mJwZQ0Og',
    appId: '1:54532140724:ios:cd3c7a03e18da3318071e1',
    messagingSenderId: '54532140724',
    projectId: 'expensexpert-b34c3',
    storageBucket: 'expensexpert-b34c3.appspot.com',
    androidClientId: '54532140724-d8p2ovngalt7tceerk41osvhnvg0v8p6.apps.googleusercontent.com',
    iosClientId: '54532140724-m0tu45m35tt8sbnfknh6j9ectju6q88p.apps.googleusercontent.com',
    iosBundleId: 'com.example.expensexpert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq9rRgALAyFxJk7YbpZ8Efvp7mJwZQ0Og',
    appId: '1:54532140724:ios:4aec12b23b9f44b98071e1',
    messagingSenderId: '54532140724',
    projectId: 'expensexpert-b34c3',
    storageBucket: 'expensexpert-b34c3.appspot.com',
    androidClientId: '54532140724-d8p2ovngalt7tceerk41osvhnvg0v8p6.apps.googleusercontent.com',
    iosClientId: '54532140724-6ceojgcj1et1bggh071g7inn6uup0tkh.apps.googleusercontent.com',
    iosBundleId: 'com.example.expensexpert.RunnerTests',
  );
}
